---

- hosts: win

  tasks:

  - name: Do azure login
    win_shell:
       az login --service-principal -u f22040ef-6462-4783-a130-8994bedbd0f0 -p jC67Q~DIYYsXtJwsj.7JLEWP3hPN93MpoObNP --tenant 463c3a4d-2165-4b7b-a5a6-84d544bf4c80

  - name: create az RG
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: westus
