---

- hosts: localhost
  
  tasks:

  - name: Create a data container
    docker_container:
      name: webcontainer
      image: prasad53/demopage:1.0
      state: started
      volumes:
       - /data